version: "3.7"

services:
  express:
    build: .
    ports:
      - "3000:3000"
    links:
      - mongodb
    depends_on:
      - mongodb
    restart: always

  mongodb:
    image: tutum/mongodb
    ports:
      - 27017:27017
    environment:
      - MONGODB_USER=userx
      - MONGODB_PASS=Ap39jKgs
      - MONGODB_DATABASE=security_master
    restart: always

  python:
    environment:
      - TZ=America/Sao_Paulo
    build: ./smart_camera
    links:
      - express
    depends_on:
      - express
      - mongodb
    restart: always
